#!/usr/bin/env python3
"""Generate the charged-EEC ISR correction table for the slides.

The deck \\input's the file this writes, so the printed numbers are always the
ones in eec_isr_correction_regions.csv and can never drift from them by hand
editing.

Entries are printed as (C_ISR - 1) x 1000, the correction in per mille.  The
correction is a few per mille everywhere, so printing 1.0088 +- 0.0009 in every
cell spends most of the table width on the digits that never change, and a
six-region table in that form does not fit the slide.

Usage:
  scripts/make_eec_region_table.py \\
      --regions /data2/yjlee/ISRsample/kkmc_1M_20260921/results/eec_isr_correction_regions.csv \\
      --out     /raid5/data/yjlee/ISR/overleaf/results/kkmc/eec_isr_region_table.tex
"""

import argparse
import csv

# CSV region name -> column header, in print order.
COLUMNS = [
    ("z < 1e-3", r"$z<10^{-3}$"),
    ("1e-3 < z < 0.1", r"$10^{-3}$--$0.1$"),
    ("0.1 < z < 0.9", r"$0.1$--$0.9$"),
    ("0.9 < z < 0.999", r"$0.9$--$0.999$"),
    ("z > 0.999", r"$z>0.999$"),
    ("all z", r"all $z$"),
]

# CSV sample label -> row label, in print order.  Herwig is last and ruled off
# because its two samples do not actually switch beam radiation.
ROWS = [
    ("Pythia 8.315", "Pythia 8.315"),
    ("Pythia 8.315 Vincia", "Pythia 8.315 Vincia"),
    ("Sherpa 3.0.3 PDFESherpa", "Sherpa 3.0.3 PDFESherpa"),
    ("Sherpa 3.0.3 YFS", "Sherpa 3.0.3 YFS"),
    ("KKMC 4.30 CEEX", "KKMC 4.30 CEEX"),
    ("Herwig 7.3.0 QED shower, ISR unchanged", "Herwig 7.3.0 QED shower"),
]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--regions", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    vals = {}
    with open(args.regions, newline="") as fh:
        for row in csv.DictReader(fh):
            vals[(row["sample"], row["region"])] = (
                float(row["c_isr"]), float(row["c_isr_err"]))

    missing = [k for k in ((s, r) for s, _ in ROWS for r, _ in COLUMNS)
               if k not in vals]
    if missing:
        raise SystemExit("missing rows in %s: %s" % (args.regions, missing[:5]))

    out = []
    out.append("% Generated by ISRStudy/scripts/make_eec_region_table.py -- do not edit.")
    out.append(r"\begin{tabular}{l" + "r" * len(COLUMNS) + "}")
    out.append(r"\toprule")
    out.append("Sample & " + " & ".join(h for _, h in COLUMNS) + r" \\")
    out.append(r"& \multicolumn{%d}{c}{\scriptsize $(\cisr-1)\times10^{3}$, "
               r"that is the correction in per mille} \\" % len(COLUMNS))
    out.append(r"\midrule")
    for i, (key, label) in enumerate(ROWS):
        if label.startswith("Herwig"):
            out.append(r"\midrule")
        cells = []
        for rkey, _ in COLUMNS:
            c, e = vals[(key, rkey)]
            cells.append(r"$%.1f \pm %.1f$" % ((c - 1.0) * 1e3, e * 1e3))
        out.append(label + " & " + " & ".join(cells) + r" \\")
    out.append(r"\bottomrule")
    out.append(r"\end{tabular}")

    with open(args.out, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote %s" % args.out)


if __name__ == "__main__":
    main()
