#!/usr/bin/env python3
"""Table of our thrust C_ISR against Anthony's, per tau bin, for the deck.

Ours comes from isr_model_cisr_thrust_bins.csv (definition B, the ALEPH one);
Anthony's from the digitised CSV, so the table says what the plot says and
nothing more.  The dip region is averaged over 0.035 < tau < 0.115 (eight
bins) with the statistical error propagated for ours.

Usage:
  scripts/make_thrust_anthony_table.py --results <dir> --out <tex>
"""
import argparse
import csv
import math
import os

OURS = [
    ("Pythia 8.315", "Pythia 8.315"),
    ("Pythia 8.315 Vincia", "Pythia 8.315 Vincia"),
    ("Sherpa 3.0.3 PDFESherpa", "Sherpa 3.0.3 PDFESherpa"),
    ("Sherpa 3.0.3 YFS", "Sherpa 3.0.3 YFS"),
    ("KKMC 4.30 CEEX", "KKMC 4.30 CEEX (ours)"),
]
ANTHONY = [
    ("collinear models", "Anthony, mean of four collinear models"),
    ("KKMCee 5.00.02", "Anthony, KKMCee 5.00.02"),
]
HEAD = [0.005, 0.015, 0.025]
DIP = [0.035 + 0.01 * i for i in range(9)]   # 0.035 .. 0.115


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    ours = {}
    with open(os.path.join(a.results, "isr_model_cisr_thrust_bins.csv"), newline="") as fh:
        for r in csv.DictReader(fh):
            if r["definition"] != "B":
                continue
            tau = round(float(r["tau_low"]) + 0.005, 3)
            ours.setdefault(r["sample"], {})[tau] = (float(r["c_isr"]), float(r["c_isr_err"]))
    ant = {}
    with open(os.path.join(a.results, "anthony_cisr_tau_digitized.csv"), newline="") as fh:
        for r in csv.DictReader(fh):
            ant.setdefault(r["series"], {})[round(float(r["tau"]), 3)] = (
                float(r["c_isr"]), float(r["reading_precision"]))

    def cell(v, e, digits=3):
        return "$%.*f \\pm %.*f$" % (digits, v, digits, e)

    def dip(d):
        vals = [d[t] for t in DIP if t in d]
        if not vals:
            return "---"
        m = sum(v for v, _ in vals) / len(vals)
        e = math.sqrt(sum(e * e for _, e in vals)) / len(vals)
        return cell(m, e)

    lines = ["% Generated by ISRStudy/scripts/make_thrust_anthony_table.py",
             r"\begin{tabular}{lrrrr}", r"\toprule",
             r"Sample & $\tau<0.01$ & $0.01$--$0.02$ & $0.02$--$0.03$ & $0.035$--$0.115$ mean \\",
             r" & \multicolumn{4}{c}{\scriptsize $0.99<T<1$ \hfill $0.98$--$0.99$ \hfill $0.97$--$0.98$ \hfill $0.885<T<0.965$} \\",
             r"\midrule"]
    for key, label in OURS:
        d = ours[key]
        lines.append(label + " & " + " & ".join(cell(*d[t]) for t in HEAD) + " & " + dip(d) + r" \\")
    lines.append(r"\midrule")
    for key, label in ANTHONY:
        d = ant.get(key, {})
        cells = [cell(*d[t]) if t in d else "---" for t in HEAD]
        lines.append(label + " & " + " & ".join(cells) + " & " + dip(d) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    with open(a.out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
