#!/usr/bin/env python3
"""Generate the charged-EEC verification tables for the 20260922 deck.

Two tables, both \\input by the deck so the printed numbers are always the ones
in the CSVs:

  eec_closure_table.tex   binned pair loop against the closed-form identity
  eec_energy_table.tex    the correction against the charged energy loss, and
                          the radiated energy measured two ways

Usage:
  scripts/make_eec_verification_tables.py --results <dir> --out <dir>
"""

import argparse
import csv
import os

ROWS = [
    ("Pythia 8.315", "Pythia 8.315"),
    ("Pythia 8.315 Vincia", "Pythia 8.315 Vincia"),
    ("Sherpa 3.0.3 PDFESherpa", "Sherpa 3.0.3 PDFESherpa"),
    ("Sherpa 3.0.3 YFS", "Sherpa 3.0.3 YFS"),
    ("KKMC 4.30 CEEX", "KKMC 4.30 CEEX"),
    ("Herwig 7.3.0 QED shower, ISR unchanged", "Herwig 7.3.0 QED shower"),
]
SQRTS = 91.1876


def read(path, key):
    out = {}
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            out[key(row)] = row
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", required=True)
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    ver = read(os.path.join(args.results, "eec_verification.csv"),
               lambda r: r["sample"])
    reg = read(os.path.join(args.results, "eec_isr_correction_regions.csv"),
               lambda r: (r["sample"], r["region"]))
    summ = read(os.path.join(args.results, "isr_model_summary.csv"),
                lambda r: (r["sample"], r["isr_state"]))

    # ------------------------------------------------------------- closure
    lines = ["% Generated by ISRStudy/scripts/make_eec_verification_tables.py",
             r"\begin{tabular}{lrrrr}", r"\toprule",
             r"Sample & $\cisr$ binned & $\cisr$ closed form & difference "
             r"& in units of $\sigma$ \\", r"\midrule"]
    for key, label in ROWS:
        if label.startswith("Herwig"):
            lines.append(r"\midrule")
        b = float(reg[(key, "all z")]["c_isr"])
        e = float(ver[key]["c_isr_exact"])
        s = float(ver[key]["c_isr_exact_err"])
        lines.append("%s & $%.6f$ & $%.6f$ & $%+.1f\\times10^{-6}$ & $%.3f$ \\\\"
                     % (label, b, e, (b - e) * 1e6, abs(b - e) / s))
    lines += [r"\bottomrule", r"\end{tabular}"]
    with open(os.path.join(args.out, "eec_closure_table.tex"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    # -------------------------------------------------------------- energy
    lines = ["% Generated by ISRStudy/scripts/make_eec_verification_tables.py",
             r"\begin{tabular}{lrrrrr}", r"\toprule",
             r"Sample & $E_{\mathrm{rad}}$ [GeV] & $\egam$ [GeV] & tagged "
             r"& \multicolumn{2}{c}{$(\cisr-1)\times10^{3}$} \\",
             r"& & & & predicted & measured \\",
             r"\midrule"]
    for key, label in ROWS:
        if label.startswith("Herwig"):
            lines.append(r"\midrule")
        v = ver[key]
        d = float(v["delta"])
        de = float(v["delta_err"])
        erad, erade = d * SQRTS, de * SQRTS
        bc = (float(summ[(key, "ON")]["mean_e_beam_collinear_gamma"]) -
              float(summ[(key, "OFF")]["mean_e_beam_collinear_gamma"]))
        frac = bc / erad if erad > 0 else 0.0
        pred = (float(v["c_isr_predicted"]) - 1.0) * 1e3
        meas = (float(v["c_isr_exact"]) - 1.0) * 1e3
        err = float(v["c_isr_exact_err"]) * 1e3
        lines.append("%s & $%.3f \\pm %.3f$ & $%.3f$ & $%.0f \\pm %.0f\\%%$ & "
                     "$%.2f$ & $%.2f \\pm %.2f$ \\\\"
                     % (label, erad, erade, bc, 100 * frac,
                        100 * frac * erade / erad, pred, meas, err))
    lines += [r"\bottomrule", r"\end{tabular}"]
    with open(os.path.join(args.out, "eec_energy_table.tex"), "w") as fh:
        fh.write("\n".join(lines) + "\n")

    print("wrote eec_closure_table.tex and eec_energy_table.tex to %s" % args.out)


if __name__ == "__main__":
    main()
