#!/usr/bin/env python3
"""Table for the KKMCee 5.00.02 slide: the two KKMC lines of this study, Anthony's
KKMCee, and the collinear models, in the three endpoint bins and the dip.

Reads the per-bin CSVs (definition B) and Anthony's digitised values, so the
numbers on the slide are the ones in the files.

Usage:
  scripts/make_kkmcee5_table.py --main <bins csv> --kkmcee5 <bins csv> --anthony <csv> --out <tex>
"""
import argparse
import csv

HEAD = [0.005, 0.015, 0.025]
DIP = [0.035 + 0.01 * i for i in range(9)]


def read_bins(path):
    out = {}
    with open(path, newline="") as fh:
        for r in csv.DictReader(fh):
            if r["definition"] != "B":
                continue
            tau = round(float(r["tau_low"]) + 0.005, 3)
            out.setdefault(r["sample"], {})[tau] = (float(r["c_isr"]), float(r["c_isr_err"]))
    return out


def cell(v, e):
    return "$%.3f \\pm %.3f$" % (v, e)


def dip(d):
    vals = [d[t] for t in DIP if t in d]
    if not vals:
        return "---"
    m = sum(v for v, _ in vals) / len(vals)
    # Digitization precision shares an axis calibration across bins; it does
    # not decrease like independent statistical errors when they are averaged.
    e = sum(e for _, e in vals) / len(vals)
    return cell(m, e)


def row(label, d):
    cells = [cell(*d[t]) if t in d else "---" for t in HEAD]
    return label + " & " + " & ".join(cells) + " & " + dip(d) + r" \\"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--main", required=True)
    ap.add_argument("--kkmcee5", required=True)
    ap.add_argument("--anthony", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    bins = read_bins(a.main)
    bins.update(read_bins(a.kkmcee5))
    ant = {}
    with open(a.anthony, newline="") as fh:
        for r in csv.DictReader(fh):
            ant.setdefault(r["series"], {})[round(float(r["tau"]), 3)] = (
                float(r["c_isr"]), float(r["reading_precision"]))

    lines = ["% Generated by ISRStudy/scripts/make_kkmcee5_table.py",
             r"\begin{tabular}{lrrrr}", r"\toprule",
             r"Sample & $0.99<T<1$ & $0.98$--$0.99$ & $0.97$--$0.98$ & $0.885<T<0.965$ \\",
             r"\midrule",
             row("KKMC 4.30 CEEX + Pythia 6.202", bins["KKMC 4.30 CEEX"]),
             row("KKMCee 5.00.02 + Pythia 8.316", bins["KKMCee 5.00.02 + Pythia 8.316"]),
             row("Anthony, KKMCee 5.00.02", ant.get("KKMCee 5.00.02", {})),
             r"\midrule",
             row("Pythia 8.315", bins["Pythia 8.315"]),
             row("Pythia 8.315 Vincia", bins["Pythia 8.315 Vincia"]),
             row("Sherpa 3.0.3 PDFESherpa", bins["Sherpa 3.0.3 PDFESherpa"]),
             row("Anthony, mean of four non-KKMC models", ant.get("collinear models", {})),
             r"\bottomrule", r"\end{tabular}"]
    with open(a.out, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote", a.out)


if __name__ == "__main__":
    main()
